apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
  - sealed-secret-db.yaml
patches:
  - path: patch-replicas.yaml
configMapGenerator:
  - name: demo-app-config
    behavior: merge
    literals:
      - environment=staging
# Image promoted manually from dev (CI only auto-updates dev overlay)
images:
  - name: demo-app
    newName: ghcr.io/lwbaleeiro/demo-app
    newTag: cb88ddb