---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-db-secret
  namespace: staging
spec:
  encryptedData:
    db-password: AgC0BwbLBDb3Hrx4Jf4Euj3bhVC7i06ovgkBQUzkZDqvtv7+egp1Xk5xjyaEFEiJ8aVB5W34EuOWHKSEG7dQZwKbGxvosOfQGgNi0cp9kNfROpCvwg24B0NLJ6S1q3TAbm6f0njJpHLxRyxd3N1NZUpiL3/kHsQZiRkJ1hn0QBsV4OM494JVXmdX4w9M2SIRXzLthvhcIrQM0ZAf+g62LsspOhINY2livSfEH0JS5gYW6TDQDae9/mpr9VB51+IBZnWzyQSquZnuBuywApZb1sGIkew3LmJzjDHYlLwBoxTEPFw2KV/XcVpGAaXeFoYwIPqsO2bwiNvD2MBtpKbs3gn1fldNXJ8C/5nRUJIZw873K3sD27lTbGMakIbxzR6fMpAhGzqYS/pcsJ4KL+vF3mEmOyeCcWt2Elz11pbMoH1Eqmp/Qgi7jHVvGFH31luyB2GYeqYMi+4o6lXL01EFt+jRlXBaSKBanbpe3cwAuGs3zbe1/Ehgb94K2bkSueKUS+3XO36lgu4gAccHK6vRMV8uq9R/0imA4dvSn5k2WTt8nuDye40REpPmB7vXqoNHn6PVo2n0dJGhNPYHYxCMGmxYwMeO6d7XbduLwXIVlFOM2awQOFXXovXggd0R+UMhiFZsPbnNb1XIDIgY2vz2/xzI2Fbw1SITEpYnqPZ6OtYmi2m/FHftSn0iiO88fnXcrX0C4gT1hGKCZ4tNLfMCS1H8X37L
    db-user: AgBN4yuYXezX1IF28DIARcpaNeAVOtW6U3HBqy6u2AJ1xBhVda2Kx+sxvZ4hMmgNzfWOitP4NWid8owTZqiOWQCVSxwSOXWKLhfEilx1Rrqj02iggnT/B1i/HmZxz8Gp1bj4lUNtnYqddVw1X+WxBjrWDooadamrVy4YrI2WLQJHwalJ6zVp3FvOS0FUrmyZLMt+7DtTlb24loMgJkF74t6RleCPBXBgW8yX6bJD90S/Yl6+40zuTgW1w0vaGZ0wIHgETZnixPDQVjZ/dW6JrqNymHK0/Bok8XX0Nw6wzstoQuS9cAKpbgqfmqNLM/Om1EOXUaWgVb0shgO3xwVWVNnOa4BKLSAJZO5nxUX9rBs305TXU6Smiwxi3Nz/3d8xuKsU+c6tBhAGKJ3WQNSEFrHm41M/oyj9PELs4HaN5t3XvKVZF8G68HEcBi69vTY8EAEAaCIz05cNnlA+jvIF7eH4kxLrLDLNhHxXnncW9F0LBS8z5j+IXtu9tlbvZ8Tv/4SEbjCdKXdSmclsXlnQgPbGpx+K0149XtBDARkgYN9swTAZt73NesPJUZJOfWuUU/46XKR3guDT1fAJU0VjdZF8aWGBG5Xl/b1+9u6lFG8qrnQp1PgBzRcqLF5JfBl/e3yQSypGgd64EA6HCImkSq6x1xl9v1FCVWzi611L6fBNpsMHUOp12zCjNuAwopq+5ltEAGTfzOmEG7sA
  template:
    metadata:
      name: demo-db-secret
      namespace: staging
