---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-db-secret
  namespace: staging
spec:
  encryptedData:
    db-password: AgCQS70dQP3cN8f9V2QxCdyL/CA+hDeAGWofuIX9Ut267bKomUn/Vpd7f+S3fdgBdJAHROJezOGNj774Z0zMxSqXJLrhs7w19LRd/Y2opv9cciMDJE2Lwk3F/U8dM7PdCyzN1PaJ+JS+5KH+chFeSqj4WML3ETezB0nMRv7A81T5KDkgpvjYhyKOpf36L/GnHX4KppO/zd66He9tAwRlJSDMRWnrrnN2bcb/ENbIBi9a0pvVMuX847Vcy6bWhiq28z5HHUBIXeOXlDhDglApXmmORgCZbFIGcl+Bv775wIzIX8JG+eTqwW8HC9lbG2mDEkufGMh+dtCjR/NvcGMOHlECdbWQLHAtTaGqXEkpmOvjv3o3GBy1Py5/jDq6k91JLqAPpPCXm9hlkV7780yeKrhg6Gwb8wWn5QmyjDjzDQZIDlMU1giYVqHHsvaMRxwmgRzzcFRBtZiBE3c8Q2t+wZuL+I3sNFNnrv0KTtJT05xGIsrX/J4N70cHFyV+inWkykfNAUyis8eCDM4MtqRFCHcSSiFG2Ey305J+uyqjjQQvDN5Xrk0E34fwJPnHRuVnZEVtbv4eUVIItzG7omILxKDQGbQB+aA1Fyu8YMesIuV3iMQtoH04Vg4PeBtM+uIxdfFDiaol/SmXAsFoJqbNK4OYcfS/SNRwNVof+AASnTDpZUbwLxu8uI2oIYyGBujf/4eLuUXz39+enmDHXw==
    db-user: AgCnHpPFiFZlzfyavrPOEsVhQjerqgkWynP/Wkl5aANMX/QYgk0OL+dmZnBGuBM9WhgO25FoX8dk4QHUnYwvOxMw3II6J3EH4aZWzXBdR8v/iqnfzhIwucvcQ+WpAb0igSoSohuNLudBHzbRgeyW6yuQEDvPfYiqhg+ktqDMCpN8zUqBA3i0hkGTGYQGORO38VN4qojok0Lg/gVMC32xzNNmDTl8HIPDuKRs6tD6Wi836fAUxpodZNAQv9rIx53RAomUIBnLibMRvQBdh5gEyn2gVSw6IHrN30JqKKZmrm+KV/xf/q7f0zh/koO9IMo4DvObOsnz+PKy3+sHCPKQfzjcZhp9U/Okm2qVFS5zsTbe0/KcaZXow+SXdV/s7pUSD2vVrrWz8oFmDfEINDoyVPKgMP5fpY5JW+kX34j2g+VM62Tiwf9RvFCvy9ZMJMHwCsxiZ8kDbg7sk6uTZpOGYiGArM4ArulMKSd5+QVPDemTTZGrCFryK8saGif4bXZkyCqTT2jsqLCo8GsVCKvOq/XkvbP4EzPmHa3Vd6nInDWFlKmLm01oy9IPYYWCr9CCtfzf30VK7gIo6ofrv5akXouZ/8kVx/HC87lInU6uJq0GSGMtiuYnS89jUjoQ4YQs2PlqAW777ASowDN+msugMPnG4qL6PMX0hobWv1LGMejXEItKyy/oxxx1mgfOmI7hbUbgKL0RBg==
  template:
    metadata:
      name: demo-db-secret
      namespace: staging
