---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-db-secret
  namespace: dev
spec:
  encryptedData:
    db-password: AgAgQhAX/zaJJvs8XDNyTMDy6Klp6R3SI+pwKDhERcN2RPdObaynXrOR/M4CyQ1geAuwzeXuGbHlVhhrN1SEAJqJZtMYqJ4Nqv9aDyyGBn+dWnX94TxwirKcykkOF3kQh3cAFBJ3s8QHCzgnB7SI/3+9YhibLlBWmyRnQ4ThssARe8B9b4N2yJojn0uzIzjMWErmXiTYB4L6yacbYdwoQG3ZPj2Vp0IuA7LVGwohQUffdc5YVnTWOwgshbllEVcGomAq1GEI3tAzAi7ly54VFxpLUGtUY2t1YxLoU2efGv0ptWvbFhe7LvuJPaQPIGE6bMOOqqqPcAKKiqEKv+kP4hLtPKt4LKYLKNden8BFnY/YAkRdkvsHXocF/rKTLUXlWe/I4W6J5L0w8k0eqrsUm8c9cMj0Ui3qs3/cZ8dyfv3wN618FHDquFQYVpQySkEZdaZfd9PqBhy5eAm9K6uPn0F3fGVVpYxraNYBDrJI8Hdm67I3+mkz+OMV8vi7ahverGsAWZuUQXYBSgE3sQEJ5TI4IcIbC3kNlewJqiRJoZDZHWaUAXyX9TRu+E22N+aJGqBnkwSGr71QkDec4xOl0qxtErUH2BPtcVTYIufzWjJ5Xos12fTiyy8mxzhaEdWEDNiQd0l7micgrqjKCIaVHF+WshvdwjCLrPb0qGkXY4cMV8h1fkqTJpfDK9aiEom7E+axL3cx2FnLsnaOaedbajbu6DY6
    db-user: AgB4Ur0BxOKK1wXrduo1hj09JTEn5nVuxjYw5OjrILBuxfuyysjcvOKF7iM6z5u4lDPSv9d6POW8gfym7nuABEWXwmWC4Ht/3XytIJWWjHQBN5gJTXAWI1A6J/0vrO7nR86Z6xKL6z0Ru7FsFIvLfb0OKqRuSY10Sfnm864BQbHE0z9qk9t9AJJk1Gp3ZPBDzf18mSA0eKHza2PVfBSDDj6k5eCMSDaBjYB11TZjOJ11OT2R5jOVbvzJa40RgO08a30mP+FvfbLqqgahNgMfmBWP1Zg2NnkEwyKjjQGP1g1Z5n4bFXoq/CaT1mWIUxdBR3pVWs7gxRShG70RvMktyj3qoDP7G8Tb93uwqdj0TLRTtwu/21hnWXEech6ovIbpw2nxuLsEKHGN7iI6AGVqQxwLLA81Z7dtuiMfwQHCU+7AOltuB8ChDf4KPq/SzjRoOT3H2VAn1biuDJVvqWPOaLgNHx2MnxGJYoMBG6aVjG7bcsEMXlX824Lco5bOfH9J+nTp33zbhZ5c8cCCmcTvlMbIVFNRa/fmKzLdkb8xNq3Z2+a/lAWHL8Y/CJ0bL3cQucPaEzbE0xSeNghhP0YyVBnvDbroRliVndqbxtMIslLuzH/8yXp0Sl1tSf1RuMm/oh5jTI+TahptzmSuqlFd55XnvnGE3EOcMfOy28Z9Rg8/5k4DvL8SMEZrB66UXTh2lfJEVMOab4lwVU+D
  template:
    metadata:
      name: demo-db-secret
      namespace: dev
