---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-db-secret
  namespace: dev
spec:
  encryptedData:
    db-password: AgBCc0fYMjnYWBa7exPpkt8rk51xshRq6PSe0+JsOv2IZ8H6JWD+VOcXf83DkA9kerTstUDuwFJ4PtI31XJL5OO9P66Qi35GWkqAGd0kQkIFSh2CJde6ASb+qzaplhCVQpcgD7+cb/XuyWoRXkOIGZcOP4vFSlUoadnZKcRjL7kq+DMJfc5Fesz7d0IoXNtlTr72MLV4/xk2VjyO13jU/yjW+m4k8mdBtICg1BZsoDfxGYRhlAfNKGgjYDcTvBYGw5ZtOry57M1H1w5OYnAMRMxgsuDzYQvzWw1XfOJAu9cIv4KSLkiy9RFo6wG+FwqBP1yxPfLqAs0a4RL53wTeYV0zx+OJS2Qfs4aKpPICwoMCV2cWAxM1XDF69ehXyRzdB9MUHAgrB1T+4xfshbcxtc9uF4rtAE0gzasTOtKmmnBR2NFO3J7HXEWAixqD0HrurHhSC7r0fSQ4NBqPbnpsdkdOK/frC86uVXq/Xn7O91lEufLMDOrrZJn0jQ+eHamblTv9dVUnbltPG/r5VvSwH3FbLL9JEdt5gtHT0mkYg7PypY6oN8HsOA3GKRB8uq7JboCn8cS9IsFPhVjrTYW7SNJnvtum8GUV4IjjZy0jZLxfKTGkQkKfkIDCRZlHxbCYRbPsDx20EA3NG8/ZW+VlEhLbfpZce4dere1DKpPuevcIEvvqLNFWlvXnVfKBhsJaOtNFJTjETLaLf163e39CoIWpLylv
    db-user: AgB2oLLnci1f3oNQ4YGKTVtJ2QV+3NtedfgujtBxF9fUkXDXrg/PgSV5phfy1zr5sKjzIfs2OK4hpY+vNaWukfK1+gRyWlKtRUOGswrXfLW3EdD1/FaciPaOtvSdGBRU2AmTZJeCyZO3381qwuL0aac4AngMh7EtFQ3ZdGEZCM2JoK+g606TJ0HRVuzbSxSshWZK1f5rndm2A/C4kNuSGmvIAuvXzNOs9b7f47TgY45wt79QMp9Nje0cvxQCQrqz23dGUJMNnSCIJBO8otN5FzVMHfuw6JL3pzwGSh7zxSe9wtMd6n/RYMaXUdKf6vpv4f1CPDUQqefouKVHooFa1xqDR9LDmFUcYIX/ZvGPFe7UvIO37drmoPnTWEDM4vEW1pqTknWYoyMEiybhEKoCNnJE/hb1nskA0ae8IZG2N0B6K/8Kvl3yXTzsD4759PEcN7On1qMCcWnzVJE6IzJtUYRp/QyQ9Y62PxWGIlfsEWLiTFTEFdApBvPJItoWACwXGVXR1KrpuujfPo+nQdyKi9EsMToshp3xjOA+ehpZNW28nxH7sSUrFSSqEid+XcEZxSfw0/L3v+x9k/skZ67h9zsmceDp3zJ00aqb/OCGF4v8X6eXDfIgNqJ7fZWhmUMbrFe1RrVgVOlRwOasbUulmn2zY0FGXyFJLauz5EC84i+3nR+Wz00v9Usmcy/yuFM6RaYXMBp/Kqu1fSLQ
  template:
    metadata:
      name: demo-db-secret
      namespace: dev
