---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-db-secret
  namespace: dev
spec:
  encryptedData:
    db-password: AgBqRwi7AxS6hVsyJGqGp3HDzBUNL4sCD0i/3SzSaERZLeS88p6/a/PbBGtUNLR85//2FGFseB0Y85Ja3ExdGP2QwwowXEVdrakvP8+zIeUk94LPSMtjRqLosqLtSVEI77gqvAcsxDGRZECyzeQVLpOrO44ZUtS9VKQJrfWCr+m5iY0s/pp+TDGZkEXnmGfKqETK+XktKGxclndK1WMGbj2BOVuefbh3McVK9BGBJXcl3BwA5QvtgwMTz5wrFs+MIG3hZ1IaaDVODS9YqBIEanfGUm4Oy8RtNkE0w1xXdwfSJI/yhZbAvL0RHZEG0iaByKQh9DpCYuP3cIjPDtKg1ucbl5TKEy6dN8oD2rp9SuHrKtlXLWhky/alLpxfGuElE85j8LvirL34gH8oBtAP218mcwHI7/pqXspbe1avs+CLdDkCLJHCT7dLY4KTmJo7B4PcaKgWaBlCMpVCuiNATTQ2gZbdN4dfwj5XmKZG2gSKMOgPqT8wu9Tr6MghgBYWz53yd/YOJypquJopXGpXpTNplyMP9s+LVSrRm7EoCQEgRey25WXWGnKP81SSHQgarY/9Tisvhffvz1lHLXcUsMelGWM/rlxN35qBRst4/356zjZyw1fkoCd+zhaL3J1U17Rjv4CdJzkxDxtFfdkzAAT/FSp3XRaiqNkSq/9Mmpfv3vPXe1zW7rgcrM/lbjKkoVGlllLSI32ve23NbsVdc9Y4sDvj
    db-user: AgCzvnETb5e942PCNs7VRiltk8/inhhENVBtSpA1HotQPp2GGKo0FE2UtdUWEBDAuTC2JD+VMb/3c9EBn13gxTSXC3FhuoqD7otufvMKvfaDZp2iRkR4ml6PQOQASLFDhKyVQOTXY27+Ofifl2LDVsZjAFsaGC/stI3OcFdwVO1CjmpIfRI99swbJtzuDU5kSAvseJLN3Alt2KUw0295bddwOuHnDSflwi+810cIirNR+5ijToCFyp2YgC3pLgTbp1Vps+F9Olx7Izn69h3x98ZUnQf1z7+9lfbTjbrHxEwbKF6QgxviRmq4hscGdnapRmB7ChEkTJBqy4HKkjBEYFyUeXbiJi/YkFrFc7cp0Jc3+Fv0aBVWA5khicQj1CEWs+kONojiqxfL6lwn0i5siO8n6b/VKckMVg048PwPFpG0crQv8DDIA3k0FRoydMkRTYGYHOXAo5tawrbX+OOYsgjjqhwaHqeLO4J32/3QIFadi0ZDyla+5WE4idpAaFS4ztRSlB3GcO6HV7jFbEFvjYhXUditnXeiCLcSyRnqti1rPHUkFq7OVAxF5ETmBKDxtuOw01ekwJW9YXC+Rp0mw1iBv+abHTW8McQ7+tOeQxUv8sQZz5UB0VENvb+SarQlRsE++W9Y1H5696IgwOxzEbqAs9lCmDerlG51rpTXCaSnqIeSf7MJ6NR/6r+qD4z8CZk9kT2K2giWCvuB
  template:
    metadata:
      name: demo-db-secret
      namespace: dev
