apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: demo-app
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: demo-app-config
                  key: environment
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: demo-db-secret
                  key: db-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-db-secret
                  key: db-password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
data:
  environment: "base"